tags:
  - name: Location
    description: Endpoints for location management and geocoding

components:
  schemas:
    Province:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "آذربایجان شرقی"
        slug:
          type: string
          example: "آذربایجان-شرقی"

    City:
      type: object
      properties:
        id:
          type: integer
          example: 2
        name:
          type: string
          example: "اهر"
        slug:
          type: string
          example: "اهر"
        popular:
          type: boolean
          example: false
        province_id:
          type: integer
          example: 1

/api/v1/locations/provinces:
  get:
    tags:
      - Location
    summary: Get list of provinces
    description: This route retrieves the full list of provinces from the `provinces.json` file.
    responses:
      200:
        description: Provinces fetched successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "لیست استان‌ها با موفقیت دریافت شد"
                    en:
                      type: string
                      example: "Provinces fetched successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: array
                  items:
                    $ref: "#/components/schemas/Province"

/api/v1/locations/cities:
  get:
    tags:
      - Location
    summary: Get list of cities
    description: This route retrieves the full list of cities from the `cities.json` file.
    responses:
      200:
        description: Cities fetched successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "لیست شهرها با موفقیت دریافت شد"
                    en:
                      type: string
                      example: "Cities fetched successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: array
                  items:
                    $ref: "#/components/schemas/City"
