/api/v1/auth/register:
  post:
    summary: Register a new user
    tags:
      - Auth
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - firstName
              - lastName
              - phone
              - email
              - username
              - password
            properties:
              firstName:
                type: string
                example: "Ali"
              lastName:
                type: string
                example: "Rezayi"
              phone:
                type: string
                example: "09154144503"
              email:
                type: string
                example: "emta137671@gmail.com"
              username:
                type: string
                example: "alirezayi"
              password:
                type: string
                example: "securePassword123"
    responses:
      201:
        description: User registered successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "با موفقیت ساخته شد"
                    en:
                      type: string
                      example: "created success"
                    status:
                      type: number
                      example: 201
                data:
                  type: object
                  properties:
                    phone:
                      type: string
                      example: "09154144503"
                    username:
                      type: string
                      example: "alirezayi"
                    email:
                      type: string
                      example: "emta137671@gmail.com"
                    firstName:
                      type: string
                      example: "Ali"
                    lastName:
                      type: string
                      example: "Rezayi"
                    role:
                      type: object
                      properties:
                        roleName:
                          type: string
                          example: "admin"
                        permissions:
                          type: array
                          items:
                            type: integer
                          example: [1, 2, 3, 4, 5, 6]
                    addresses:
                      type: array
                      items:
                        type: object
                      example: []
                    createdAt:
                      type: string
                      format: date-time
                      example: "2025-04-19T04:41:49.867Z"
                    updatedAt:
                      type: string
                      format: date-time
                      example: "2025-04-19T04:41:49.867Z"

/api/v1/auth/login:
  post:
    summary: Login user
    tags:
      - Auth
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - login
              - password
            properties:
              login:
                type: string
                example: "alirezayi"
              captcha:
                type: string
                example: "1234535"
              captchaKey:
                type: string
                example: "345435435435345"
              password:
                type: string
                example: "securePassword123"
    responses:
      200:
        description: User login successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "ورود با موفقیت انجام شد"
                    en:
                      type: string
                      example: "Login successful"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    accessToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    refreshToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

/api/v1/auth/send-otp:
  post:
    summary: Send OTP code to email or mobile number
    tags:
      - Auth
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - identifier
            properties:
              identifier:
                type: string
                description: ایمیل یا شماره موبایل کاربر
                example: "emta137671@gmail.com"
    responses:
      200:
        description: OTP sent successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "کد OTP با موفقیت ارسال شد"
                    en:
                      type: string
                      example: "OTP sent successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    "otpSecret":
                      type: string
                      example: "726787"

/api/v1/auth/verify-otp:
  post:
    summary: Verify OTP code
    tags:
      - Auth
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - code
              - identifier
            properties:
              code:
                type: string
                example: "123456"
                description: کد یکبار مصرف ارسال شده
              identifier:
                type: string
                example: "emta137671@gmail.com"
                description: ایمیل یا شماره موبایل کاربر
    responses:
      200:
        description: OTP verified successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "کد با موفقیت تأیید شد"
                    en:
                      type: string
                      example: "OTP verified successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    accessToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    refreshToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

/api/v1/auth/refresh-token:
  post:
    summary: Generate new access token using refresh token
    tags:
      - Auth
    description: Validates the provided refresh token and returns a new access token
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - refreshToken
            properties:
              refreshToken:
                type: string
                example: "your-refresh-token-here"
    responses:
      200:
        description: User login successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "ورود با موفقیت انجام شد"
                    en:
                      type: string
                      example: "Login successful"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    accessToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                    refreshToken:
                      type: string
                      example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

/api/v1/auth/me:
  get:
    summary: Get user profile
    tags:
      - Auth
    description: Get the authenticated user's profile using access token
    responses:
      200:
        description: User profile retrieved successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "پروفایل کاربر با موفقیت دریافت شد"
                    en:
                      type: string
                      example: "User profile retrieved successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    phone:
                      type: string
                      example: "09154144503"
                    username:
                      type: string
                      example: "alirezayi"
                    email:
                      type: string
                      example: "emta137671@gmail.com"
                    firstName:
                      type: string
                      example: "Ali"
                    lastName:
                      type: string
                      example: "Rezayi"
                    role:
                      type: object
                      properties:
                        roleName:
                          type: string
                          example: "admin"
                        permissions:
                          type: array
                          items:
                            type: integer
                          example: [1, 2, 3, 4, 5, 6]
                    addresses:
                      type: array
                      items:
                        type: object
                      example: []
                    createdAt:
                      type: string
                      format: date-time
                      example: "2025-04-19T04:41:49.867Z"
                    updatedAt:
                      type: string
                      format: date-time
                      example: "2025-04-19T04:41:49.867Z"

/api/v1/auth/forgot-password:
  post:
    summary: Reset user password
    tags:
      - Auth
    description: Sends a password reset link to the user by validating the provided email.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
            properties:
              email:
                type: string
                format: email
                description: The email of the user that needs to reset the password.
                example: "user@example.com"
    responses:
      200:
        description: Password reset link sent successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "لینک بازنشانی رمز عبور با موفقیت ارسال شد"
                    en:
                      type: string
                      example: "Password reset link sent successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    email:
                      type: string
                      example: "user@example.com"

/api/v1/auth/reset-password/{token}:
  post:
    summary: Reset user password
    tags:
      - Auth
    description: Sends a password reset link to the user by validating the provided email.
    parameters:
      - name: token
        in: path
        required: true
        schema:
          type: string
        description: ID of the address to retrieve
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - email
            properties:
              newPassword:
                type: string
                format: newPassword
                description: The password is required.
                example: "123*****3"
    responses:
      200:
        description: Password reset link sent successfully
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: object
                  properties:
                    fa:
                      type: string
                      example: "لینک بازنشانی رمز عبور با موفقیت ارسال شد"
                    en:
                      type: string
                      example: "Password reset link sent successfully"
                    status:
                      type: integer
                      example: 200
                data:
                  type: object
                  properties:
                    email:
                      type: string
                      example: "user@example.com"
